Backlog 16875 improve deletion
Jahia/site-settings-seo pull request #107
Opened 2023-01-24 14:22 UTC by jsinovassin

2023-01-25 10:07 UTC, jahia-carp submitted a review, later dismissed

2023-01-30 07:55 UTC, dgriffon requested changes
Very good !

2023-01-30 07:55 UTC, dgriffon commented on src/javascript/components/Context/VanityUrl.context.jsx
> +    const site = data?.jcr?.result?.site;
What is the behavior if no site is resolved ? Currently it will generate an error line 30

2023-01-30 07:55 UTC, dgriffon commented on src/javascript/components/Editable.jsx
> +    if (!edit && !isCreateMode) {
Strange statement, is there other mode than edit or create?

2023-01-30 07:55 UTC, dgriffon commented on src/javascript/components/Editable.scss
> +    background: #FFF !important
important should be avoided

2023-01-30 07:55 UTC, dgriffon commented on src/javascript/components/Editable.scss
> +    background: #FFF !important
important should be avoided

2023-01-30 07:55 UTC, dgriffon commented on src/javascript/components/Toolbar/Toolbar.scss
> +    background-color: #21282f;
Is it ok to use hardcoced colors ? can't we get it from a theme or something?

2023-01-30 07:55 UTC, dgriffon commented on src/javascript/components/VanityList/VanityUrlListDefault.jsx
> +        <>
That opening component is not needed

2023-01-30 08:59 UTC, jsinovassin commented on src/javascript/components/Editable.jsx
> +    if (!edit && !isCreateMode) {
It is not the create or edit mode of Jahia. It's the mode of the vanity url value field. If we are not creating or editing a vanity url, it's simply an text which is displayed. And when you click on it, we switch to the edit mode

2023-01-30 14:47 UTC, dgriffon approved these changes

2023-01-30 14:55 UTC, merged