BACKLOG-20594: not add alternate or canonical if they exist already
Jahia/site-settings-seo pull request #110
Opened 2023-01-30 13:21 UTC by jahia-carp

https://jira.jahia.org/browse/BACKLOG-20594

2023-01-30 14:17 UTC, jsinovassin commented
site-settings-seo-test-module.properties file can be removed as well

2023-01-30 14:29 UTC, jsinovassin requested changes

2023-01-30 14:29 UTC, jsinovassin commented on test-module/pom.xml
> +    <version>1.0.0-SNAPSHOT</version>
It should be better ta have the same version than the parent for this module

2023-01-30 14:29 UTC, jsinovassin commented on test-module/pom.xml
> +    <scm>
This part can be removed

2023-01-30 14:29 UTC, jsinovassin commented on test-module/src/main/resources/META-INF/rules.drl.disabled
> +package org.jahia.test.sitesettingsseotestmodule.rules
You can delete this file as it is not used

2023-01-30 14:29 UTC, jsinovassin commented on test-module/src/main/resources/jnt_template/html/template.with-seo-links.jsp
> +<div class="bodywrapper"><!--start bodywrapper-->
Not a big problem but I think comments like this does not bring much information in the code

2023-01-30 14:29 UTC, jsinovassin commented on test-module/src/site/apt/index.apt
> +site-settings-seo-test-module
Do we know if this file is used somewhere?

2023-01-30 14:29 UTC, jsinovassin commented on test-module/src/site/site.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Do we need this file?

2023-01-30 14:29 UTC, jsinovassin commented on tests/cypress/e2e/basic.test.cy.ts
> +    const createPage = (parent, name, template = undefined) => {
Is it necessary to set the default value to undefined for template?

2023-01-30 14:29 UTC, jsinovassin commented on tests/cypress/fixtures/graphql/jcrPublicationStatus.graphql
> +            aggregatedPublicationInfo(language: "en", subNodes: true) {
Not mandatory, but it could be nice to have language as a parameter

2023-01-30 14:48 UTC, jahia-carp commented on test-module/pom.xml
> +    <version>1.0.0-SNAPSHOT</version>
Fixed

2023-01-30 14:48 UTC, jahia-carp commented on test-module/pom.xml
> +    <scm>
Done

2023-01-30 14:48 UTC, jahia-carp commented on test-module/src/main/resources/META-INF/rules.drl.disabled
> +package org.jahia.test.sitesettingsseotestmodule.rules
Done

2023-01-30 14:48 UTC, jahia-carp commented on test-module/src/main/resources/META-INF/site-settings-seo-test-module.tld.disabled
> +<?xml version="1.0" encoding="UTF-8" ?>
Done

2023-01-30 14:48 UTC, jahia-carp commented on test-module/src/main/resources/jnt_template/html/template.with-seo-links.jsp
> +<div class="bodywrapper"><!--start bodywrapper-->
Done

2023-01-30 14:49 UTC, jahia-carp commented on test-module/src/site/apt/index.apt
> +site-settings-seo-test-module
Removed

2023-01-30 14:49 UTC, jahia-carp commented on test-module/src/site/site.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Removed

2023-01-30 14:49 UTC, jahia-carp commented on tests/cypress/e2e/basic.test.cy.ts
> +    const createPage = (parent, name, template = undefined) => {
Fixed not really necessary for this test

2023-01-30 15:31 UTC, jkevan requested changes
I'm not sure that the algorithm implement is correct.
I understand that we wanted:
- do not calculate **alternates** in case there is already 1+ **alternate** link tag
- do not calculate **canonical** in case there is already 1+ **canonical** link tag

But here it seem's that:
- in case there is a **canonical** tag, but no **alternates** tag, then **alternates** tags wont be calculated. (and I think we should calculate the **alternates** because there is no **alternates** tags, but should not calculate the **canonical** only.)

So the detection should be smarter and make the difference between canonical and alternates presence.
To be confirmed with PM, but it seem's that's what we agreed on during the 3 amigos session.

2023-01-30 15:58 UTC, jahia-carp commented on tests/cypress/fixtures/graphql/jcrPublicationStatus.graphql
> +            aggregatedPublicationInfo(language: "en", subNodes: true) {
Done

2023-01-31 16:01 UTC, jsinovassin approved these changes

2023-01-31 16:50 UTC, jkevan approved these changes

2023-01-31 16:51 UTC, merged