Backlog 20632 fix issues on set new canonical when previous one is locked
Jahia/site-settings-seo pull request #121
Opened 2023-02-10 14:24 UTC by jahia-carp

https://jira.jahia.org/browse/BACKLOG-20632

2023-02-10 15:30 UTC, jsinovassin requested changes

2023-02-10 15:30 UTC, jsinovassin commented on core/src/javascript/components/AddVanityUrl.jsx
> +        if (mappings[0].defaultMapping === true && atLeastOneCanonicalLockedForLang(urls, lang)) {
Could it be replaced by 
`if (mappings[0].defaultMapping && atLeastOneCanonicalLockedForLang(urls, lang)) {`
?

2023-02-10 15:30 UTC, jsinovassin commented on core/src/javascript/components/Utils/Utils.jsx
> +    return urls.some(url => url.default.mixinTypes.find(mixin => mixin.name === 'jmix:markedForDeletion') && url.default.language === lang && url.default.default === true);
Maybe you could remove `=== true ` from `url.default.default === true`

2023-02-10 15:30 UTC, jsinovassin commented on core/src/javascript/components/Utils/Utils.jsx
> +export const atLeastOneCanonicalLockedForLang = (urls, lang) => {
Be careful, The query returning the urls in content editor is not returning the mixinTypes, you could have an null pointer when calling url.default.mixinTypes.find

2023-02-14 12:54 UTC, jahia-carp commented on core/src/javascript/components/AddVanityUrl.jsx
> +        if (mappings[0].defaultMapping === true && atLeastOneCanonicalLockedForLang(urls, lang)) {
Fixed

2023-02-14 12:54 UTC, jahia-carp commented on core/src/javascript/components/Utils/Utils.jsx
> +    return urls.some(url => url.default.mixinTypes.find(mixin => mixin.name === 'jmix:markedForDeletion') && url.default.language === lang && url.default.default === true);
Fixed

2023-02-14 12:54 UTC, jahia-carp commented on core/src/javascript/components/Utils/Utils.jsx
> +export const atLeastOneCanonicalLockedForLang = (urls, lang) => {
Fixed

2023-02-14 13:27 UTC, jsinovassin requested changes

2023-02-14 13:27 UTC, jsinovassin commented on core/src/javascript/components/SiteSettingsSeoApp.jsx
> +        let variables = buildTableQueryVariablesAllVanity({selectedLanguageCodes: this.state.loadParams.selectedLanguageCodes, path: siteInfo.path, lang: lang, poll: polling ? SiteSettingsSeoConstant
The poll property is not used in buildTableQueryVariablesAllVanity, it is not necessary to pass it as a param

2023-02-14 13:27 UTC, jsinovassin commented on core/src/javascript/components/SiteSettingsSeoApp.jsx
>                      path={siteInfo.path}
Path and lang can be removed here. They are not used in VanityUrlTableData anymore

2023-02-14 13:27 UTC, jsinovassin commented on core/src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoCardApp.jsx
>                      path={path}
Path and lang can be removed here. They are not used in VanityUrlTableData anymore

2023-02-14 13:27 UTC, jsinovassin commented on core/src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoCardApp.jsx
> +        let variables = buildTableQueryVariablesOneNode({selectedLanguageCodes: this.props.languages, path: path, lang: lang, poll: polling ? SiteSettingsSeoConstants.TABLE_POLLING_INTERVAL : 0, ...t
The polling param is not necessary here

2023-02-14 13:41 UTC, jahia-carp commented on core/src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoCardApp.jsx
> +        let variables = buildTableQueryVariablesOneNode({selectedLanguageCodes: this.props.languages, path: path, lang: lang, poll: polling ? SiteSettingsSeoConstants.TABLE_POLLING_INTERVAL : 0, ...t
Cleaned

2023-02-14 13:41 UTC, jahia-carp commented on core/src/javascript/components/SiteSettingsSeoApp.jsx
>                      path={siteInfo.path}
Cleaned

2023-02-14 13:41 UTC, jahia-carp commented on core/src/javascript/components/SiteSettingsSeoApp.jsx
> +        let variables = buildTableQueryVariablesAllVanity({selectedLanguageCodes: this.state.loadParams.selectedLanguageCodes, path: siteInfo.path, lang: lang, poll: polling ? SiteSettingsSeoConstant
Cleaned thanks

2023-02-14 13:48 UTC, jsinovassin submitted a review, later dismissed

2023-02-15 10:51 UTC, jsinovassin approved these changes

2023-02-15 10:51 UTC, merged