Backlog 15718 update js config
Jahia/site-settings-seo pull request #13
Opened 2021-03-23 11:55 UTC by AKarmanov

## JIRA

https://jira.jahia.org/browse/BACKLOG-15718

## Description

Webpack config update, clean up and basic migration. CSS/Theme is broken, some functionality may be buggy, lint still has 500 errors etc.

2021-03-23 16:20 UTC, gflores-jahia commented on webpack.config.js.old
> +let path = require('path');
Remove .old file

2021-03-23 17:00 UTC, rknj requested changes

2021-03-23 17:00 UTC, rknj commented on .circleci/config.yml
> +    default: false
```suggestion
parameters:
  AUDITCI_LEVEL:
    type: string
    default: "moderate"
  TESTS_PATH:
    type: string
    default: "tests/"
  TESTS_IMAGE:
    type: string
    default: "jahia/site-settings-seo"
  MODULE_ID:
    type: string
    default: "sitemap"
  TESTRAIL_PROJECTNAME:
    type: string
    default: "Site Settings SEO Module"
  GITHUB_SLUG:
    type: string
    default: "jahia/site-settings-seo"
  MODULE_ID:
    type: string
    default: "site-settings-seo"
  PRIMARY_RELEASE_BRANCH:
    type: string
    default: "master"
  RELEASE_ID:
    type: string
    default: ""
  RELEASE_VERSION:
    type: string
    default: ""
  IS_RELEASE:
    type: boolean
    default: false
  UPDATE_SIGNATURE:
    type: boolean
    default: false
```

2021-03-23 19:08 UTC, AKarmanov commented on webpack.config.js.old
> +let path = require('path');
Ah, yes I forgot about that one

2021-03-23 20:59 UTC, gflores-jahia approved these changes

2021-03-24 08:39 UTC, rknj approved these changes

2021-03-24 11:02 UTC, merged