BACKLOG-21306 : migrate tests to cypress
Jahia/site-settings-seo pull request #156
Opened 2023-07-21 14:32 UTC by ksagnard

2023-07-24 08:10 UTC, jsinovassin requested changes

2023-07-24 08:10 UTC, jsinovassin commented on tests/cypress/e2e/edit/addVanityUrlUi.cy.ts
> +            vanityUrlUi.getNewVanityUrlRow().then(() => {
Why is it necessary to call getNewVanityUrlRow here?

2023-07-24 08:10 UTC, jsinovassin commented on tests/cypress/page-object/VanityUrlUi.ts
> +        // We do not select manually language = 'en' as it is the default language
Can this check causes some fail if the default language is not english?

2023-07-24 08:26 UTC, ksagnard commented on tests/cypress/e2e/edit/addVanityUrlUi.cy.ts
> +                errorMsg: 'Menu not opened in required time',
fixed

2023-07-26 15:50 UTC, jsinovassin commented on tests/cypress/page-object/VanityUrlUi.ts
> +    enterVanityUrlValues(vanityValue: string, canonical = false, language = 'en') {
It would be nice to rename this function in fillVanityValues

2023-07-26 15:50 UTC, jsinovassin commented on tests/cypress/page-object/VanityUrlUi.ts
> +    startAddvanityUrl() {
It would be nice to rename this function in fillVanityValues clickOnAddVanityUrl

2023-07-26 17:55 UTC, ksagnard commented on tests/cypress/page-object/VanityUrlUi.ts
> +    startAddvanityUrl() {
fixed thanks for your comments

2023-07-27 10:55 UTC, jahia-carp approved these changes

2023-07-27 10:57 UTC, merged