BACKLOG-21277 : migrate test case seo on content
Jahia/site-settings-seo pull request #158
Opened 2023-07-24 14:49 UTC by ksagnard

2023-07-25 05:38 UTC, jahia-carp requested changes

2023-07-25 05:38 UTC, jahia-carp commented on tests/cypress/e2e/edit/addVanityUrlonContentUi.cy.ts
> +        cy.visit(Cypress.env('JAHIA_URL') + '/vanityEdited')
You can avoid duplicate code by using a method like for instance:

```
    const visitAndCheck = (url, expectedText) => {
        cy.visit(Cypress.env('JAHIA_URL') + url);
        cy.url().should('include', url).should('not.include', '.html');
        cy.get('h2').invoke('text').then((text) => {
            expect(text).contains(expectedText);
        });
    };
	
visitAndCheck('/vanityEdited', 'Some interresting news');
```

2023-07-25 21:57 UTC, ksagnard commented on tests/cypress/e2e/edit/addVanityUrlonContentUi.cy.ts
> +        cy.visit(Cypress.env('JAHIA_URL') + '/vanityEdited')
thanks, its fixed now

2023-07-26 07:01 UTC, jahia-carp approved these changes

2023-07-26 07:41 UTC, merged