QA-14916: Add cypress to test Toolbar comportment
Jahia/site-settings-seo pull request #167
Opened 2023-09-13 10:22 UTC by jahia-carp

https://jira.jahia.org/browse/QA-14916

2023-09-14 16:55 UTC, jsinovassin requested changes

2023-09-14 16:55 UTC, jsinovassin commented on tests/cypress/e2e/edit/checkToolbarVanityYrlsPageUi.cy.ts
> +import { addVanityUrl } from '@jahia/cypress'
There is a typo in the name of the file

2023-09-14 16:55 UTC, jsinovassin commented on tests/cypress/e2e/edit/checkToolbarVanityYrlsPageUi.cy.ts
> +        vanityUrlsPage.toolbarShouldBeOpen(false)
We should use cy.logout() at the end of the test when there is a cy.login() otherwise we could have some opened session remaining.

2023-09-14 16:55 UTC, jsinovassin commented on tests/cypress/e2e/edit/checkToolbarVanityYrlsPageUi.cy.ts
> +    it('Check toolbar comportment on delete permanently vanities', function () {
It should better to set vanity urls instead of vanities

2023-09-14 16:55 UTC, jsinovassin commented on tests/cypress/e2e/edit/checkToolbarVanityYrlsPageUi.cy.ts
> +        cy.wait(1000)
Don't we have a better solution to check that the vanity urls are marked for deletion, like checking if the lock icon is displayed for the lines we deleted

2023-09-14 16:55 UTC, jsinovassin commented on tests/cypress/page-object/vanityUrls.page.ts
> +    selectAllVanityUrls() {
It would be better to have a parameter in this function to specify the page where we want to select all vanity urls. 
As this function only select all vanity urls of the first opened page

2023-09-14 16:55 UTC, jsinovassin commented on tests/cypress/page-object/vanityUrls.page.ts
> +    clickOnToolbarTargetButton(buttonRole) {
clickOnToolbarTargetButton, clickOnDeleteDialogTargetButton, clickOnDeletePermanentlyDialogTargetButton are pretty much the same function, we should modify them to avoid such duplicate code

2023-09-14 16:55 UTC, jsinovassin commented on tests/cypress/page-object/vanityUrls.page.ts
> +    toolbarShouldBeOpen(check = true) {
From my point of view the check should be done directly in the test, not in the page object.
For me the page object should represent a page, modal, ...
As there is no feature that check that the toolbar is open, we should not have it here.
But you can confirm with a QA to have his/her opinion.

2023-09-15 13:54 UTC, jahia-carp commented on tests/cypress/e2e/edit/checkToolbarVanityYrlsPageUi.cy.ts
> +import { addVanityUrl } from '@jahia/cypress'
Fixed

2023-09-15 13:54 UTC, jahia-carp commented on tests/cypress/e2e/edit/checkToolbarVanityYrlsPageUi.cy.ts
> +        vanityUrlsPage.toolbarShouldBeOpen(false)
Fixed

2023-09-15 13:54 UTC, jahia-carp commented on tests/cypress/e2e/edit/checkToolbarVanityYrlsPageUi.cy.ts
> +    it('Check toolbar comportment on delete permanently vanities', function () {
Updated

2023-09-15 13:55 UTC, jahia-carp commented on tests/cypress/e2e/edit/checkToolbarVanityYrlsPageUi.cy.ts
> +        cy.wait(1000)
Currently no but I opened a ticket and add a todo

2023-09-15 13:55 UTC, jahia-carp commented on tests/cypress/page-object/vanityUrls.page.ts
> +    selectAllVanityUrls() {
Thanks :-) fixed

2023-09-15 13:55 UTC, jahia-carp commented on tests/cypress/page-object/vanityUrls.page.ts
> +    clickOnToolbarTargetButton(buttonRole) {
Thanks :-) fixed

2023-09-15 13:58 UTC, jahia-carp commented on tests/cypress/page-object/vanityUrls.page.ts
> +    toolbarShouldBeOpen(check = true) {
I understand the point of view, but we already do this for instance on jexperience. 
It could actually be interesting to discuss it within the team and agree on a “nomemclature”. 
Thanks for the feedbacks :-)

2023-09-15 14:24 UTC, jsinovassin approved these changes

2023-09-17 15:16 UTC, merged