Backlog 9625 vanity in ce
Jahia/site-settings-seo pull request #35
Opened 2021-05-17 12:23 UTC by AKarmanov

## JIRA

https://jira.jahia.org/browse/BACKLOG-9625

## Description

Integrate vanity url in content editor

2021-05-21 18:47 UTC, gflores-jahia reviewed
Hey Alex, I think changeset can go as-is in terms of correctness but I do have some component and dependency design questions/suggestions. Maybe worth to go over next week to see if any of my comments makes sense or maybe something that I'm just not understanding at the moment.

2021-05-21 18:47 UTC, gflores-jahia commented on src/javascript/components/SiteSettingsSeoApp.jsx
> +const assembleWithHoc = function(component) {
I get the reason why we're doing an export here and being imported in contentEditor/SeoApp but the way we're passing it around just doesn't look right from component perspective. 

Seems in this case assembleWithHoc is shared on both components/SeoApp and contentEditor/SeoApp. Maybe it can be refactored to a common module (through SeoWrapper maybe?) instead of being passed around from here (which would also maybe mean extracting styles). Other option maybe is since components/SeoApp is a parent, maybe makes more sense to expose through inheritance. I'm open to discussions if we have other options.

2021-05-21 18:47 UTC, gflores-jahia commented on src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoApp.jsx
> +class SiteSettingsSeoCard extends SiteSettingsSeoApp {
can we rename file maybe to SiteSettingsSeoCardApp since there's already same file in components/? and also maybe change to match the class name as well.

2021-05-21 18:47 UTC, gflores-jahia commented on src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoEntry.jsx
> +const SiteSettingsSeoCardEntry = props => <SiteSettingsSeoWrapper component={SiteSettingsSeoCard} {...props}/>;
can we rename file to SiteSettingsSeoCardEntry since there's already same file in components/? Probably better to match it with the component name as well

2021-05-21 18:47 UTC, gflores-jahia commented on src/javascript/components/contentEditor/VanityUrlTableData/VanityUrlTableData.jsx
> +                        {this.props.children(rows, totalCount, numberOfPages)}
any reason why we're duplicating this instead of just TableData class? By comparing it seems that we're only ignoring totalCount and numberOfPages but not sure why we can't just ignore that in the SeoApp.

2021-05-25 14:48 UTC, XiangYuHe commented on src/javascript/components/Deletion.jsx
> +        zIndex: 2010
Curious why we are doing this? (Is it because we might be opening multiple dialogs?)

2021-05-25 16:45 UTC, AKarmanov commented on src/javascript/components/Deletion.jsx
> +        zIndex: 2010
yes, a dialog over another dialog

2021-05-25 16:55 UTC, AKarmanov commented on src/javascript/components/AddVanityUrl.jsx
> +import {SiteSettingsSeoConstants} from './SiteSettingsSeoEntry';
It was that way when I found it (in the original file) and as the goal was not to begin modifications of original components I kept it as is doing minimal changes necessary. But I can see how it can be even more confusing with extra import/export in between, I'll move it.

2021-05-25 17:14 UTC, AKarmanov commented on src/javascript/components/contentEditor/VanityUrlTableData/VanityUrlTableData.jsx
> +                        {this.props.children(rows, totalCount, numberOfPages)}
To be honest I though about keeping original component and passing a prop to use a specific query but given that we no longer need some of the props and use it with a different component I chose to duplicate and modify it instead. With the difference in query and query variables it's easier to manage and we don't have to worry about verifying both sides of the app incase there are changes to one side and there's no added complexity in terms of logic. I think we can extract gqlContentNodeToVanityUrlPairs though and put it in utils file or something like that.

2021-05-25 17:19 UTC, AKarmanov commented on src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoEntry.jsx
> +const SiteSettingsSeoCardEntry = props => <SiteSettingsSeoWrapper component={SiteSettingsSeoCard} {...props}/>;
I was thinking about symmetry between two parts on this one the one above but sure we can rename them no problem.

2021-05-25 17:35 UTC, gflores-jahia commented on src/javascript/components/SiteSettingsSeoApp.jsx
> +const assembleWithHoc = function(component) {
Agreed with the complexity here. Let's go through initial commit first then we can revisit. We can keep this as-is for now.

2021-05-25 17:42 UTC, gflores-jahia commented on src/javascript/components/contentEditor/VanityUrlTableData/VanityUrlTableData.jsx
> +                        {this.props.children(rows, totalCount, numberOfPages)}
honestly I could go either way on this one (keeping duplicates or having them combined). Makes sense for now to go this route and keeping legacy logic intact. I'm ok keeping as-is for now as well.

I'm also either way on refactoring gqlContentNodeToVanityUrlPairs out. If easy enough yeah, let's do it but if not, we can keep until we find ourselves changing that part of the code later on.

2021-05-25 17:46 UTC, gflores-jahia commented
Based from the replies, we can do the renaming the component file names and refactoring SiteSettingsSeoConstants as part of the PR changes. Other refactoring suggestions we can revisit again.

2021-05-25 17:49 UTC, gflores-jahia requested changes
Based from the replies, we can do the renaming the component file names and refactoring SiteSettingsSeoConstants as part of the PR changes. Other refactoring suggestions we can revisit again.

2021-05-25 18:28 UTC, gflores-jahia approved these changes

2021-05-25 18:49 UTC, merged