BACKLOG-16138: Display domain across seo url
Jahia/site-settings-seo pull request #39
Opened 2021-06-09 20:18 UTC by XiangYuHe

## JIRA

https://jira.jahia.org/browse/BACKLOG-16138

## Description

Minor edit to use the root URL inputted by the user in the sitemap UI panel.

2021-06-11 19:03 UTC, gflores-jahia submitted a review, later dismissed

2021-06-15 13:41 UTC, gflores-jahia commented on src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java
> +        String serverName = renderContext.getSite().getProperty("sitemapIndexURL").getValue().getString();
fyi there is also a convenience method `getPropertyAsString()` that does same thing

2021-06-15 13:42 UTC, gflores-jahia approved these changes, later dismissed

2021-06-15 21:09 UTC, XiangYuHe commented on src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java
> +        String serverName = renderContext.getSite().getProperty("sitemapIndexURL").getValue().getString();
Yup good catch

2021-06-16 13:06 UTC, gflores-jahia requested changes

2021-06-16 13:06 UTC, gflores-jahia commented on src/main/java/org/jahia/modules/sitesettingsseo/utils/Utils.java
> +        URL url = new URL(urlString);
It might be better to use URI package to parse than roll our own implementation. See here: https://stackoverflow.com/a/9608008

2021-06-16 13:06 UTC, gflores-jahia commented on src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java
> +        String serverName = Utils.getServerName(renderContext.getSite().getPropertyAsString("sitemapIndexURL"));
maybe we should default to relative url or `renderContext.getURLGenerator().getServer()` in case something goes wrong with parsing

2021-06-16 15:19 UTC, XiangYuHe commented on src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java
> +        String serverName = Utils.getServerName(renderContext.getSite().getPropertyAsString("sitemapIndexURL"));
I would suggest to keep the exception so we know there is an error
Instead of assume that is it successful when it is not

2021-06-16 15:20 UTC, XiangYuHe commented on src/main/java/org/jahia/modules/sitesettingsseo/utils/Utils.java
> +        URL url = new URL(urlString);
Based on the comments
It seems like URI maybe handle some cases better (being said I believe the implementation is the same regardless if we use URL or URI) Updated

2021-06-16 16:20 UTC, gflores-jahia approved these changes, later dismissed

2021-06-16 16:20 UTC, gflores-jahia commented on src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java
> +        String serverName = Utils.getServerName(renderContext.getSite().getPropertyAsString("sitemapIndexURL"));
Either way I think we just need a way to inform users if anything is wrong with the URL. Logging is enabled for now in case anything goes wrong with parsing.

2021-06-16 16:53 UTC, gflores-jahia approved these changes

2021-06-16 17:12 UTC, merged